spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/reddit_bot
   username: postgres
   password: postgres
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

# noinspection SpringBootApplicationYaml
reddit:
  username:
  refresh:
    token:
  client:
    id:
    secret:
# noinspection SpringBootApplicationYaml
discord:
  bot:
    token:
  admin:
    server:
      id: your_admin_server_id
    user:
      id: your_discord_id
# noinspection SpringBootApplicationYaml
firebase:
  storage:
    bucket:
      name:
  adminsdk:
    file:
      name: